// <auto-generated />
namespace WhyWhere.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class justendmealready : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(justendmealready));
        
        string IMigrationMetadata.Id
        {
            get { return "201809252340536_just end me already"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
